name: Sync To Gitee
on: [push, delete, create]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Sync to Gitee
       uses: wearerequired/git-mirror-action@master
     env:
     # 注意在Settings->Secrets配置GITEE_RSA_PRIVATE_KEY
     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
     with:
     # 注意替换为你的GitHub源仓库地址
     # 注意替换为你的Gitee目标仓库地址
     destination-repo: git@gitee.com:dawenxi-tech/MonkeyKingScripts.git
