name: Sync To SRHT
on: [push, delete, create]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Sync to SRHT
       uses: wearerequired/git-mirror-action@master
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SR_HT_RSA_PRIVATE_KEY }}
       with:
         source-repo: https://github.com/Mount-Huaguo/MonkeyKingScripts.git
         destination-repo: git@git.sr.ht:~dawenxi/MonkeyKingScripts
